### ISSUE TITLE
use message of event in command

### ISSUE THREAD

**Issue by xenoterracide** [sardemff7/purple-events#10]
Is there a way with "Events to order" to pass the message, or whatever the content of the body is?

**Comment by sardemff7** [comment]
There is no code for that, no
You could use a sightly more complex setup, with purple-events, purple-eventc and eventd, that would add a big set of features to do almost anything with the events. You would not need most of the eventd features, since the (eventd) exec plugin has no extra dependencies

I do not intent to add such a feature to purple-events, to keep it really minimal
Plus, it’s in maintenance mode as I do not use Pidgin/Finch as much as I used to

Out of curiosity, what are you trying to achieve here?

**Comment by xenoterracide** [comment]
I was to send system notifications, since it seems for some reason that use of live notify is not yet built in. Pigeon itself though is seeming kind of on maintenance mode. I haven't really been using Linux for years due to having a Mac at work, and I decided to give pigeon a go again and it doesn't really seem like it's changed at all. So I've kind of given up on it too.

PS speech to text so I know it's spelled differently.

**Comment by sardemff7** [comment]
For notifications, there are two combinations you can use:
- purple-events + [purple-libnotify+](https://github.com/sardemff7/purple-libnotify-plus)
- purple-events + [purple-eventc](https://clients.eventd.org/purple) + [eventd](https://www.eventd.org) with its own notifications, or as a relay to another libnotify daemon, but with more customization possible
